theme: jekyll-theme-minimal
remote_theme: pages-themes/
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
gem "github-pages", group: :jekyll_plugins
logo: "/assets/images/RMC-Pic.jpg"
title: Rubén Martínez Cárdenas
description: Welcome to my homepage

