theme: jekyll-theme-minimal
remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
gem "github-pages", group: :jekyll_plugins
<img src="assets/images/RMC-Pic.jpg" alt="My pic" width="100/"></a>
title: Rubén Martínez Cárdenas
description: Welcome to my homepage
